apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jpnw6ly71-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jpnw6ly71-java-quarkus-gitops